/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Web3Voting } from "./Web3Voting";
export * as factories from "./factories";
export { Web3Voting__factory } from "./factories/Web3Voting__factory";
